MODEL_TYPE: llava
LLAVA_MODEL_PATH: models/llava-1.5-7b-hf
LLM_MODEL_NAME: models/llava-1.5-7b-hf
CHECKPOINT_DIR: checkpoints
KNOWLEDGE_BASE_DIR: knowledge_base
KNOWLEDGE_DIR: knowledge_base
RESULTS_DIR: results
INFERENCE_CONFIDENCE_THRESHOLD: 0.5
MAX_INFERRED_OBJECTS: 8
VISUAL_CONTEXT_FILTER_STUFF_MERGED: true
VISUAL_CONTEXT_FILTER_KEYWORDS: true
